# Generated by Django 5.1.3 on 2024-11-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="direccion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="perfil_riesgo",
            field=models.CharField(
                choices=[("bajo", "Bajo"), ("medio", "Medio"), ("alto", "Alto")],
                default="medio",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Los grupos a los que pertenece el usuario.",
                related_name="usuario_groups",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permisos específicos de usuario.",
                related_name="usuario_user_permissions",
                to="auth.permission",
            ),
        ),
    ]
